### PR TITLE
Clarify Project date sort labels

### PR DESCRIPTION
**Pull request by frankyma**
Match asc desc to cypher

### CODE REVIEW

**Comment by CarsonF** [comment]
This seems backwards...

**Comment by frankyma** [comment]
It's not, that's how Cypher orders dates.  You can check on master it's backwards right now

**Comment by CarsonF** [comment]
I mean logically. Sorting dates _ascending_ should be _oldest to newest_.
Wikipedia agrees:
> A standard order is often called ascending (corresponding to the fact that the standard order of numbers is ascending, i.e. A to Z, 0 to 9), the reverse order descending (Z to A, 9 to 0). For dates and times, ascending means that earlier values precede later ones e.g. 1/1/2000 will sort ahead of 1/1/2001.
https://en.wikipedia.org/wiki/Sorting#:~:text=A%20standard%20order%20is%20often,of%201%2F1%2F2001.

If cypher does it backwards we should handle that on the API.

**Comment by frankyma** [comment]
you know what, our **Naming** for the date sort description is unclear.  We use words like "closest' and "furthest", but we really should use words like "earliest" and "latest".  You and I had different definitions of what closest and furthest meant.

**Comment by CarsonF** [comment]
That's a good point. closest/furthest is could be interrupted different based on whether the date is in the past or future. I agree that earliest/latest removes that ambiguity.

**Comment by frankyma** [comment]
Changed

**Review by CarsonF — COMMENTED** [review]
Can you flip the the props back?

**Comment by frankyma** [comment]
Sure switched back

**Review by CarsonF — APPROVED** [review]
👍

**Pull request merged**
