### PR TITLE
[Bugfix][FE 318] pronounciation guide

### PR DESCRIPTION
**Pull request by frankyma**
Added word guide

### CODE REVIEW

**Comment by CarsonF** [comment]
How about the LanguageForm too?

**Comment by frankyma** [comment]
> How about the LanguageForm too?

You're right.  Changed...not sure about the placeholder though? `placeholder="Enter the Pronunciation Guide of Public Name"`

**Comment by CarsonF** [comment]
Hmm yeah that looks weird. Maybe keep the placeholder how it was.

**Comment by frankyma** [comment]
> Hmm yeah that looks weird. Maybe keep the placeholder how it was.

changed

**Pull request merged**
