### PR TITLE
Fix 2167

### PR DESCRIPTION
**Pull request by elisabeth-sorrell**
API PR: https://github.com/SeedCompany/cord-api-v3/pull/2354
fixes #2167

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466500749) by [Unito](https://www.unito.io)
┆Link To Item: https://seed-company-squad.monday.com/boards/3451697530/pulses/3466500749

### CODE REVIEW

**Review by CarsonF — APPROVED** [review]
LGTM just need to fix lint error

**Comment by elisabeth-sorrell** [comment]
I've run `yarn lint` and `yarn type-check` and didn't find any errors....?

**Comment by CarsonF** [comment]
Hmm yeah idk why CI cannot find the artifact. Maybe a rebase on develop would fix it and would be good in general?

**Comment by elisabeth-sorrell** [comment]
Could it be because the API PR is either stale or had a failed build?

**Comment by sethmcknight** [comment]
This lived to the end of its lifetime and died

**Pull request closed without merging**
