### PR TITLE
Allow clean submit for lookup field create dialogs

### PR DESCRIPTION
**Pull request by blakekrammes**

### CODE REVIEW

**Review by CarsonF — DISMISSED** [review]
Good catch @blakekrammes!

**Comment by blakekrammes** [comment]
Thanks!

**Comment by blakekrammes** [comment]
Looks like gql-gen is failing.

**Comment by CarsonF** [comment]
Can you rebase?

**Comment by blakekrammes** [comment]
Thanks! Rebased.

**Review by CarsonF — APPROVED** [review]

**Pull request merged**
