### PR TITLE
Add status on lang engagement detail

### PR DESCRIPTION
**Pull request by frankyma**
Screen Shot 2020-10-20 at 4 59 19 PM

### CODE REVIEW

**Comment by CarsonF** [comment]
Would you mind putting it before paratext id? I think it's more important than that.

**Comment by frankyma** [comment]
@CarsonF should I make status first on internship engagement also for consistency?  For reference here's the current order
Screen Shot 2020-10-21 at 8 53 54 AM

**Comment by CarsonF** [comment]
Yeah let's put the status first on both. Then the date range, which looks to be missing from language engs. Then specifics for each type.

**Comment by frankyma** [comment]
Put status and date range first on both

**Review by CarsonF — APPROVED** [review]
Thanks @frankyma

**Pull request merged**
