### PR TITLE
Filter Projects by "My Projects"

### LINKED ISSUE #468: Filter Projects by 'My Projects'
Add an option to the Project List filters for 'My Projects' that displays only the projects a user is a Team Member of.

### PR DESCRIPTION
**Pull request by glassblowerscat**
Closes #468 

Add `mine` field to `ProjectFilterOptions`

### CODE REVIEW

**Review by CarsonF — CHANGES_REQUESTED** [review]
I think we want to default to `mine`. Maybe we could change this to `all` / "Show All Projects"?

**Comment by glassblowerscat** [comment]
> I think we want to default to `mine`. Maybe we could change this to `all` / "Show All Projects"?

From a UX perspective, I kind of think the better thing would be to just change the default. That way the text ("Only Show My Projects") explains why some projects aren't shown. I'm always a little annoyed when some things are hidden by default and the option to change that is labeled "Show all", because it doesn't tell me what is hidden

**Comment by CarsonF** [comment]
I agree that "show all" isn't very indicative of the other option.

I wanted to replace the toggle switch here for that reason with [two toggle buttons](https://material-ui.com/components/toggle-button/#exclusive-selection). That way labels for either option could be represented. Kinda like this:


Screen Shot 2020-09-21 at 4 40 30 PM

I'm working on an `EnumField` that could be used for here for that.

**Comment by glassblowerscat** [comment]
> I think we want to default to `mine`.

So, as far as I can tell, our `useProjectFilters` hook will always return an empty object from the default filters, which means there's no obvious way to use it to set a default filter that's different than the API default. We could do something like this:

```
const [filters, setFilters] = useProjectFilters();

const defaultMine = {
  ...filters,
...(filters.mine ? null : { mine: true }),
}

  const { data } = useProjectListQuery({
    variables: {
      input: {
        ...sort.value,
        filter: filters,
      },
    },
  });
```

But that feels a little gross. It seems more like if we want this to be the default we should change it on the API side. Thoughts, @CarsonF?

**Comment by CarsonF** [comment]
Yes there is a mismatch here between the UI & the API, but the API mutation is called `projects` not `myProjects`. I think the fact that this is defaulted to my projects is a UI concern.

And yes I believe the default values should be left off of the query parameters. Ideally this change doesn't leave the `ProjectFilterOptions.tsx` file.

It's possible that this is enough:
```tsx
  mine: BooleanParam(true),
```
SwitchField might also need a default as well:
```tsx
<SwitchField name="mine" defaultValue={true} />
```

**Comment by glassblowerscat** [comment]
> It's possible that this is enough:
> 
> ```
> export const useProjectFilters = makeQueryHandler({
>   mine: BooleanParam(true),
>   ...
> ```
> 
> `<SwitchField name="mine" defaultValue={true} />`

I made both of these changes in a recent commit, but the `filters` object is still empty. The `SwitchField` does mount in `true` position, but it has no effect on what gets queried

**Comment by glassblowerscat** [comment]
@CarsonF this is ready to review again, unless you want to wait for the `EnumField` to be ready first

**Review by CarsonF — APPROVED** [review]
> @CarsonF this is ready to review again, unless you want to wait for the EnumField to be ready first

Nope, looks great! I just rebased and tweaked the commit message.

**Pull request merged**
