### PR TITLE
Prevent Calendar Popper from Overflowing

### PR DESCRIPTION
**Pull request by rdonigian**
https://seed-company-squad.monday.com/boards/3451697530/views/78801638/pulses/7106310825

### CODE REVIEW

**Review by CarsonF — COMMENTED** [review]
😧 can you explain this change? Why isn't it the default?

**Comment by rdonigian** [comment]
> 😧 can you explain this change? Why isn't it the default?

Renato posted the image of what's going on when a user zooms, which is cutting off the bottom of the calendar from an overflow issue.  This ensures the calendar stays on the page as a whole.

**Comment by rdonigian** [comment]
Here is a before and after 
Screenshot 2024-08-02 at 1 42 30 PM
Screenshot 2024-08-02 at 1 42 50 PM

**Comment by rdonigian** [comment]
I don't believe I see anything in our config that's preventing that from being the default.

**Review by willdch — APPROVED** [review]
I like it, I like it a lot.  
Great work @rdonigian

**Review by CarsonF — APPROVED** [review]
LGTM. Can we just add a comment saying this modifier prioritizes keeping the popup on screen sacrificing keeping the text input visible?

**Review by CarsonF — APPROVED** [review]
Thanks @rdonigian

**Pull request merged**
