### PR TITLE
Update Global Innovations to Growth Partners label

### PR DESCRIPTION
**Pull request by rdonigian**
https://seed-company-squad.monday.com/boards/3451697530/views/78801638/pulses/6787472941

API PR: https://github.com/SeedCompany/cord-api-v3/pull/3265

### CODE REVIEW

**Comment by rdonigian** [comment]
API PR: https://github.com/SeedCompany/cord-api-v3/pull/3265

**Comment by CarsonF** [comment]
It's gotta be in the PR description

**Review by CarsonF — APPROVED** [review]

**Review by CarsonF — CHANGES_REQUESTED** [review]
in lieu of [this](https://github.com/SeedCompany/cord-api-v3/pull/3265#issuecomment-2263416767), let's revert everything but the label changes here.

Let's also call it "Growth Partner's Client"

**Comment by CarsonF** [comment]
@rdonigian sorry one more change.
```diff
- Growth Partners
+ Growth Partners'
```

**Review by CarsonF — APPROVED** [review]

**Pull request merged**
